corpus = [
    "will you be my friend",
    "you and i will always be friends",
    "today is the first of november",
    "i saw a bear today",
    "she is in her room",
    "let us go to the park",
    "i have a few questions",
    "i like her too",
    "it is sunny outside",
    "i really like it here",
    "that door is open",
    "this letter is for you",
    "you are really nice",
    "he is my brother",
    "i want to go with you",
    "i watch movies on my ipad",
    "what will you do now",
    "can i say something",
    "this is my favorite cookie",
    "they are here",
    "can you pick me up at the mall",
    "i am sorry but she is away",
    "we are going to watch a movie",
    "this is his box",
    "this card came from my cousin",
    "that is a really cool trick",
    "that is not what i want",
    "i cannot open it",
    "i will not open it",
    "will you come by and see me",
    "she is very happy",
    "do you like blue or yellow",
    "her role as an english teacher is very important",
    "what are you thinking of",
    "i want to go there",
    "this is their house",
    "what can i do for you",
    "who can help me",
    "can you get me my eyeglasses",
    "what if i fail",
    "would you help me out",
    "i have her book",
    "all my favorite books are on this shelf",
    "my mom is coming to visit",
    "can we make our projects together",
    "what is this movie about",
    "do you know where this place is",
    "i will help you find that place",
    "as soon as she is here i will talk to her",
    "i live up in the mountains",
    "she is one of my english teachers",
    "there was a time i liked to play golf",
    "there are so many things i want to learn",
    "this is the year i am finally going to learn english",
    "i am so sorry",
    "i think i need to lie down",
    "when will i see you again",
    "which of these slippers are yours",
    "please give this to them",
    "please give them some of the apples i brought home",
    "can you give me some apples",
    "there are so many people at the mall today",
    "please take home some of these apples",
    "my puppy ran into the woods",
    "just close your eyes",
    "did you see that",
    "i heard him singing earlier",
    "your mom is here",
    "can your mom and dad come to the party",
    "could you help me with my project",
    "i want to watch this now",
    "i like this cake better than the other one you showed me",
    "i like this bag better than the other one you showed me",
    "i like these shoes better than the other ones you showed me",
    "how do i turn this on",
    "we had breakfast and then we went to church",
    "i need to read its manual",
    "this is our home now",
    "two cheeseburgers please",
    "can i have some more milk shake",
    "do you like these ribbons",
    "do you want these ribbons",
    "can you look this way",
    "please look this way",
    "she was my very first teacher",
    "she was also my best friend",
    "i have new shoes",
    "i am crying because i am sad",
    "today is national friendship day",
    "i have more stickers at home",
    "how do i use this",
    "there is no electricity now",
    "there is a man outside looking for you",
    "one thing led to another",
    "give her these pearls",
    "we shared many dreams together",
    "you know me so well",
    "you are my only friend here",
    "those boots belong to my friend",
    "can you tell me which way to go",
    "she is the one he is been waiting for",
    "i am very upset right now",
    "her grandmother is sick",
    "she cannot even stand on her own",
    "i will be right back",
    "have you had any luck on your research",
    "you are a good person",
    "that woman looks so polished",
    "your faith will see you through tough times",
    "do you want to go with us",
    "this is the best day of my life",
    "i just saw a child cross the street by herself",
    "did you go there",
    "i have to go to work",
    "let us go down",
    "you may take your seats",
    "let us have dinner after work",
    "should i buy this dress",
    "call me when you get home okay",
    "i want to travel and see the world",
    "i cannot wait for this day to be over",
    "my cousin goes to school here",
    "i still think you should go",
    "can you try to be nicer to him",
    "what is in that box",
    "as soon as i get home i am going to start watching that series",
    "this is my last slice of cake i promise",
    "can you ask the waiter to bring us some wine",
    "i need some wine tonight",
    "i need some wine too",
    "i feel so tired i just need to relax and unwind",
    "i have three sisters",
    "when was the last time you saw them",
    "check out the state of that shed it is falling apart",
    "i am never going to drink wine again",
    "over the years we have become really close",
    "this is just between you and me",
    "give me a high five",
    "i really like your painting",
    "i have something for you",
    "she is the most beautiful girl i have ever seen",
    "i will have another glass of wine please",
    "i love you guys so much",
    "you are like family to me",
    "i want to get my own place",
    "get out of my room",
    "i want you to leave",
    "please put down that book and listen to me",
    "i feel so old",
    "i can wait for you here while you shop",
    "i did not mean to sound so angry",
    "can you turn on the lights",
    "can we keep the lights on tonight",
    "i have always been a diligent student",
    "this is why i do not go out anymore",
    "why will you not let him know how you feel",
    "this ice cream place is great for families with kids",
    "hey we are wearing the same shirt",
    "i have this big crush on brad pitt",
    "the group sitting across our table is so noisy",
    "where do i begin with this huge project",
    "she may seem quiet but she is really outgoing once you get to know her",
    "japan is such a beautiful country",
    "i need help with my math homework",
    "can we talk in private",
    "where were you last night",
    "if only i could turn back time",
    "the problem is we think we have plenty of time",
    "this is a great to start to learn the english language",
    "do not let go of my hand",
    "this might actually work",
    "the american culture is so dynamic",
    "can you show me how to use this vacuum cleaner",
    "this is my favorite part of the movie",
    "what is the story about",
    "i am so against domestic abuse",
    "this place is wonderful",
    "she kept saying this over and over again",
    "he is such an annoying person",
    "can we play that game again",
    "just a few more errands and i am done",
    "what an interesting case you are working on now",
    "that is the most interesting story i have ever heard",
    "i had a rough week",
    "will you keep me company",
    "where are we going",
    "what is wrong with the airport system",
    "can you give each of them an apple",
    "i am right this time",
    "this community program for teens is really helpful",
    "did you hear that",
    "i am so sleepy",
    "i have a question for you",
    "during the session i saw him fall asleep",
    "i have to work this weekend",
    "we can play soccer next weekend instead",
    "i hope the government does something about the poverty in this country",
    "if you see a bear here run for your life",
    "i have a small favor to ask you",
    "i have a number of favors to ask you",
    "please turn off the television",
    "i always bring pepper spray with me",
    "let us move on to the next tourist spot",
    "i really like you",
    "the night is young",
    "i am going to live like there is no tomorrow",
    "mr morris is here",
    "you have a point",
    "i believe in you",
    "just hold my hand",
    "i am going to see you today",
    "please bring a pen",
    "what will happen if you do not submit your report on time",
    "this is the next best thing",
    "i cannot live without my phone",
    "before i go to bed i always wash my face",
    "there is a large amount of data online about that topic",
    "that is all i know about dinosaurs",
    "i have a million questions about this book",
    "we must watch this movie together",
    "can we go home now",
    "i hid it under my bed",
    "i filled the tub with water",
    "his room is at the end of the corridor",
    "can you write me a prescription for this",
    "his mother is a very lovely woman",
    "this area of this house needs to be fixed",
    "that virus has become a national concern",
    "she needs money to buy her medicine",
    "she shared her story to the media",
    "she is so young and so hopeful",
    "it is a fact shopping can improve your mood",
    "it is that time of the month",
    "just because she is different it does not mean she is bad",
    "you have a lot of explaining to do",
    "turn right when you reach the corner",
    "let us study our english lessons together",
    "can i borrow your english book",
    "she has the pink eye",
    "i love my job",
    "describe yourself in one word",
    "though you are angry now i am sure you will forget about this later",
    "his business is thriving",
    "this is not an issue for me",
    "whose side are you on anyway",
    "always be kind even to strangers",
    "there are four seasons in a year",
    "let us head back it is freezing out here",
    "we have gone too far and now we are lost",
    "she has long black hair",
    "she has long brown hair",
    "they both love chocolate ice cream",
    "i have two little boys with me now",
    "the house is so quiet without you",
    "i hope you say yes",
    "after all this time he has finally learned to love",
    "ever since his mom died he has been cranky and angry at the world",
    "that was such a long time ago",
    "please provide me with a list of your services",
    "do you have a specific dental service to treat this",
    "we went around the block",
    "you are a good friend",
    "you are important to me",
    "my father is so important to me",
    "let us sit outside together",
    "he is away right now",
    "until when will you be away",
    "with great power comes great responsibility",
    "i have been checking his temperature every hour",
    "let us play a game",
    "i buy from his bakery as often as i can",
    "there is a long line at the grocery cashier",
    "i stay away from political discussions",
    "it is the end of an era",
    "among all my pets he is my most favorite",
    "have you ever tried this cake",
    "can you stand still for a minute",
    "what you did was so bad",
    "i cannot lose you",
    "i want to buy this bag however i need to save up for it first",
    "she is a member of the babysitter s club",
    "let us pay for our groceries",
    "there is a law against jay walking",
    "i want you to meet my aunt",
    "let us go inside my car",
    "this is the city that never sleeps",
    "i am almost done with my report",
    "did you remember to include the summary in your report",
    "can we continue working tomorrow",
    "great let me set an appointment for you",
    "our community is very tight knit",
    "there is so much to learn in the english language",
    "what is your name",
    "i can give you five reasons why you need to watch that video",
    "i once had a puppy named bark",
    "i love my white sneakers",
    "she is the least productive among all the employees",
    "she was our class president back in high school",
    "i would love to learn more about the english language",
    "what is her real name",
    "what can we change so that things will get better",
    "they hired a team to do the design of their new office",
    "she is laughing every minute of every day",
    "this is the best potato salad i have ever tasted",
    "i have several old clothes i need to donate",
    "it was your idea to go to the beach remember",
    "she worked out hard to achieve a toned body",
    "this is the information i need",
    "there is nothing we can do now",
    "three years ago i visited japan for the first time",
    "you are right i want to go back there",
    "just lead the way and i will follow",
    "i feel awkward in these social gatherings",
    "i understand how you feel",
    "whether in big groups or small groups i always feel a little shy at first",
    "looking back i knew i was always an introvert",
    "let us watch the sun set on the horizon",
    "they are together now",
    "i will follow you home",
    "you will always have me around",
    "every parent is trying hard and doing their best",
    "you are only allowed to go out today",
    "please stop that",
    "why is your face so red",
    "you can ask me for anything",
    "did you create that presentation it was so good",
    "this is public property",
    "i already asked him to resend his report",
    "could you speak a little louder",
    "the others have not arrived yet",
    "i read somewhere that this house is haunted",
    "what level are you in that game",
    "do you allow your kids to play outside the house",
    "is it okay if we add a bit of sugar to the tea",
    "welcome to my office",
    "how much did you spend on your last shopping spree",
    "you left the door open",
    "this is my work of art",
    "are you sure you want to do this alone",
    "you are such a brave little boy",
    "the war has finally ended",
    "she is my history professor",
    "are you going to her party tonight",
    "we support everyone within our small community",
    "we want everyone to grow and thrive in their careers",
    "the result of this outreach program is amazing",
    "are you open to teaching on weekends",
    "where can we change her diaper",
    "it is such a beautiful morning",
    "come take a walk with me",
    "you are the reason i came home",
    "her blood pressure has gotten really low",
    "we can win this match if we work together",
    "how is your research going",
    "that girl is in my class",
    "i have seen that guy in school before",
    "i come to work so early every day",
    "let us buy some food",
    "before i talk to you i want to tell you something",
    "the moment she walked in the room her puppy started to jump and dance again",
    "he cooked this turkey himself",
    "i am loving the cold night air here",
    "you are the best teacher ever",
    "do not force him to play with other kids",
    "can i offer you a ride home",
    "boys that is enough playing for today",
    "you both need to change into your sleep clothes now",
    "i just want you to get the best education",
    "your dog ran across the park",
    "although she felt tired she still could not sleep",
    "do you think she will still remember me after ten years",
    "her foot got caught in one of the ropes",
    "this is the second time she got late this month",
    "there is a boy in her class who keeps pulling her hair",
    "maybe we can have ice cream for dessert",
    "he took a step toward her",
    "will you be able to send me your report today",
    "what is the average marrying age these days",
    "the cat ran off with the dog",
    "they have a generous return policy",
    "everything is on sale",
    "i love what you are wearing",
    "wait give me time to process everything you are telling me",
    "i love music",
    "around twenty people attended including bob and beth",
    "i hope you consider my project proposal",
    "how did that appear out of nowhere",
    "i am actually just heading out",
    "i am going to buy these shoes",
    "he is probably still asleep",
    "give him a break he is only human",
    "is it alright if you wait for a few minutes",
    "this blow dryer has served me well for years",
    "let us visit the sunday market",
    "i do not want my cat to die let us take him to the vet please",
    "please send the package to my address",
    "you cannot expect much from their poor service",
    "i cannot wait to go home",
    "i did sense that something was not okay",
    "he is going to build his dream house",
    "you can stay with me for a few weeks",
    "be careful you might fall",
    "oh no i left my phone at home",
    "we have to act as one nation",
    "what is your plan this time",
    "do not cut your hair",
    "we met in college",
    "music is an interest of mine",
    "death is such a heavy topic for me",
    "what course did you take up in college",
    "is there someone who can go with you",
    "what an exciting experience",
    "i am scared to check what is behind that door",
    "i cannot reach him he will not answer his phone",
    "this is a local business",
    "smoking can kill you",
    "i have six books about psychology",
    "these remain on the top shelf",
    "wow the effect of that mascara is great",
    "can i use your phone",
    "yeah he did call me earlier",
    "he did suggest that to me",
    "we were in the same english class",
    "where is the remote control",
    "it is so challenging to discipline kids these days",
    "i do not care about what you think",
    "perhaps we can arrive at a compromise",
    "there is a little bird outside my window",
    "i am running late for my doctor appointment",
    "that test was so hard",
    "he is over there by the soccer field",
    "is anyone else coming",
    "can we pass by the grocery store",
    "she was my former housemate",
    "we can sell your old couch online",
    "it is a major issue for the project",
    "sometimes i forget to turn off the porch lights",
    "they will require you to show your id",
    "can i tag along your road trip",
    "this news development is really interesting",
    "they can take care of themselves",
    "i read her report and it was great",
    "she is going to play the role of elsa",
    "your singing has gotten so much better",
    "some countries are facing an economic crisis",
    "the government must make an effort to solve this",
    "his grades have gone up",
    "please decide where to eat",
    "how would you rate the hotel service",
    "they have strong customer service here",
    "maybe it is possible to change their bathroom amenities",
    "my heart is so full",
    "she got the patent for the drug she has created to cure cancer",
    "can you show me how to solve this puzzle",
    "you are a wonderful leader",
    "watch her face light up when you mention his name",
    "hearing his mom's voice is all he needs right now",
    "my wife is away for the weekend",
    "i have the whole house to myself",
    "the police have questioned him about the incident",
    "this relaxation technique really eases my mind",
    "i can finally move out from my old apartment",
    "my baby niece likes to pull my hair",
    "i give her tickles in return",
    "the best things in life are free",
    "his dad is in the military",
    "this is the price you pay for lying",
    "did you report this to the police",
    "i am praying for less stress this coming new year",
    "according to the weather report it is going to rain today",
    "this is a big decision for me",
    "i will explain everything later i promise",
    "his son is so cute",
    "i hope i will have a son one day",
    "even if they have broken up they still remain friends",
    "that rash could develop into something more serious",
    "this view is amazing",
    "they have taken their relationship to the next level",
    "can you carry my bag for me",
    "this town is extremely quiet",
    "there is a road that leads to the edge of the woods",
    "you cannot drive there you need to walk",
    "he broke his arm during practice",
    "it is true i am leaving the company",
    "animal abuse is now a federal felony",
    "do not break the law",
    "you better learn how to follow rules",
    "what is the difference between happiness and contentment",
    "i forgot to thank her for the pie she sent us",
    "did you receive the pie i sent you",
    "i value our friendship so much",
    "their brand has gone international",
    "this building is so tall",
    "you next action is going to be critical",
    "my work load is so full now",
    "a great leader is a great model of how to do things",
    "he wants to join the soccer team",
    "christmas is my favorite season",
    "their society is holding a fund raiser",
    "i am going home because my mom needs me",
    "how much is the current income tax",
    "the director yelled cut",
    "i am too early for my appointment",
    "please position your hand properly when drawing",
    "that basketball player is cute",
    "i agree he is cute",
    "i especially like his blue eyes",
    "can we record the minutes of this meeting please",
    "did you pick a color theme already",
    "is that what you are going to wear for the party",
    "you can use a special paper for your invitations",
    "some special paper are even scented",
    "please leave some space to write down your phone number",
    "the ground is shaking",
    "a new island was formed after that big earthquake",
    "i need your support for this project",
    "we are holding a big event tonight",
    "our official wedding photos are out",
    "whose umbrella is this",
    "what does it matter anyway",
    "everyone thinks i stole that file",
    "i hate being the center of attention",
    "the couple is on their honeymoon now",
    "this site is so big",
    "it is the end of an era",
    "this project file is due tomorrow",
    "he hit the burglar with a bat",
    "all moms are their child s home base",
    "what musical activity can you suggest for my toddler",
    "my son can draw a star",
    "i saw him draw it while he was writing on the table",
    "i need to enroll him to a good preschool",
    "there is a basketball court near our house",
    "fresh farm produce is the best",
    "i could eat that all day",
    "my sister is dating an american",
    "i love to teach english lessons",
    "could you buy me some cooking oil at the store",
    "just half a liter please",
    "the situation is getting out of hand",
    "i thought you said this was going to be easy",
    "the cost of fuel has increased",
    "the fuel industry is hiking prices",
    "will our government figure out how to fix this problem",
    "i cannot bear to face this horrendous traffic again and again",
    "let us cross the street",
    "there is an image of him stored inside my mind",
    "the bike itself is pretty awesome",
    "plus it has a phone holder",
    "i either walk or commute to work",
    "how can we simplify this data",
    "could you cover for me during emergencies",
    "i am quite satisfied with their work",
    "picture this a lake a cabin and lots of peace and quiet",
    "that picture is so clear inside my head",
    "let us practice our dance number",
    "that is a piece of cake",
    "their plane is going to land soon",
    "this is her most recent social media post",
    "describe yourself in one word",
    "this is my favorite product in their new line of cosmetics",
    "the doctor is in",
    "can you post this up on the wall",
    "the patient is in so much pain now",
    "she is a factory worker",
    "i saw that on the news",
    "i have to pass this english test",
    "let us watch a movie later",
    "there is a certain kind of magic in the air now",
    "santa lives up north",
    "i love christmas",
    "this letter is very personal",
    "why did you open and read it",
    "will you support him",
    "i simply will not tolerate bad behavior",
    "this is the third time you have lied to me",
    "write about the advantages of technology",
    "let us catch up soon please",
    "watch your step",
    "her baby is so adorable",
    "can you turn on the computer please",
    "you need to type in your password",
    "can i have your attention please",
    "can you draw this for me",
    "that film is absolutely mind blowing",
    "he is a republican candidate",
    "that tree has been there for generations",
    "you are my source of strength",
    "i will wear a red dress tonight",
    "he nearly died in that accident",
    "their organization is doing great things for street kids",
    "let me choose a color",
    "we have to see the cause and effect of this experiment",
    "i will cut my hair short for a change",
    "can you look at the items i bought",
    "what is the point of all this",
    "we are living in the 21st century mary",
    "the evidence clearly shows that he is guilty",
    "i will buy window curtains next week",
    "sometimes life can be difficult",
    "you have to listen to your teacher",
    "i will launch my course soon",
    "i hope they understand our culture better",
    "my target is to have 1 billion dollars in my account by the end of the year",
    "is there any chance that you can do this for me",
    "my brother always have my back",
    "now put that energy into walking",
    "they covered a period of twenty years",
    "have seen my course already",
    "i will go to the beach in summer",
    "sometimes less is more",
    "i just realize that i have a meeting today",
    "i have a hundred dollars that i can lend you",
    "i am available to work on your project",
    "plant a seed",
    "it was likely a deer trail",
    "it was the perfect opportunity to test her theory",
    "i am sure there is a latin term for it",
    "it was just a short stay at the hotel",
    "i already passed my letter of intent",
    "do you know the condition i am in",
    "i have no choice",
    "let us meet out at meeting place",
    "i am a single parent",
    "it is the rule of the law",
    "my daughter knows how to read now",
    "i will take this up with the administration",
    "i am headed south",
    "my husband just bought me a ring for my birthday",
    "it will be debated at the congress",
    "she is our floor manager",
    "i handled their election campaign",
    "she had nothing material to report",
    "the population of the nearest big city was growing",
    "i wish you well",
    "i am going to call the bank",
    "the economy is booming",
    "she needs medical assistance",
    "i will take her to the nearest hospital",
    "i saw you in church last sunday",
    "please close the door",
    "there are a thousand reasons to learn english",
    "taking a risk can be rewarding",
    "what is your current address",
    "make sure your smoke alarm works in case of fire",
    "the future is full of hope",
    "that is the wrong answer",
    "we need to involve the police",
    "what is your defense or reason you did this",
    "does anyone know the answer",
    "let us increase your test score",
    "some apartment buildings have security",
    "i need to go to the bank to withdraw some money",
    "i can clean up by myself",
    "i can certainly help clean up",
    "if you drive west you will arrive in california",
    "my favorite sport is soccer",
    "can you see the board",
    "seek and you will find",
    "lobster is 20 dollars per pound",
    "my favorite subject is english",
    "where can i find a police officer",
    "this is a private party",
    "let us take a 15 minute rest",
    "this dog s behavior is excellent",
    "a used car can be a good deal",
    "your performance can be affected by your sleep",
    "i do not want to fight with you",
    "throw me the ball",
    "you are a top student",
    "let us finish reading this quickly",
    "in the past my english was not as good as it is today",
    "my goal is to speak english fluently",
    "my second goal is to increase my confidence",
    "i go to bed around 10pm",
    "i would like to order a book",
    "the author of this series is world famous",
    "i need to fill up my gas tank",
    "i represent my family",
    "turn off your phone and the tv and focus on your studies",
    "it is great having foreign friends",
    "please do not drop the eggs",
    "let us make a plan",
    "the hospital needs people to give blood",
    "once upon a time a princess lived in a castle",
    "let us contract an agency to help with marketing",
    "the door says push not pull",
    "i love walking in nature",
    "my favorite color is blue",
    "no is one of the shortest complete sentences",
    "i cleaned the bathroom most recently so i think it is your turn this time",
    "i am going to the store to buy some bread",
    "reduce reuse and recycle are the ways to help the environment",
    "i like the sound of wind chimes",
    "please take notes during the lesson",
    "i feel fine",
    "before the movie let us buy popcorn",
    "near far wherever you are i do believe that the heart goes on",
    "the environmental movement is an international movement",
    "please turn to page 62",
    "you can enter the building on the left",
    "let me share my idea",
    "ice cream has more calories than water",
    "most people can find something in common with each other",
    "we had a poor harvest this year because it was so dry",
    "this pen does not work try the other one",
    "this cleaner is natural there are not any chemicals in it",
    "we watched the car race on tv",
    "thank you for your concern but i am fine",
    "what is your favorite tv series",
    "his job earns a significant amount of money",
    "these earrings do not match but they are similar",
    "do not touch the stove it is still hot",
    "learning a new language is fun",
    "put a flower in each vase",
    "i usually shop at the corner store",
    "i did not expect his response to come so soon",
    "my phone is dead let me charge it",
    "the sun will rise at 7 00 a m",
    "what kind of animal is that",
    "heredity is a factor in your overall health",
    "i have lived in this city for over a decade",
    "did you read that newspaper article",
    "he wants to shoot arrows at the target",
    "drive east for three miles",
    "i save all my cans for recycling",
    "there are seven slices of pie left",
    "taylor swift is a recording artist",
    "i wish that mosquito would go away",
    "he painted a colorful street scene",
    "that shop has a good stock of postcards",
    "retail sales is a good career for some people",
    "despite the rain we will still have the picnic",
    "there is good shopping in central london",
    "that recipe takes eight cups of flour",
    "we have not had any problems thus far",
    "i will propose a treatment plan for your injury",
    "the town is just beyond those mountains",
    "kittens make me happy",
    "use exactly one teaspoon of salt in that recipe",
    "a coat will protect you from the cold weather",
    "the cat slowly approached the bird",
    "teach your children not to lie",
    "what size is that shirt",
    "do you think a dog is a good pet",
    "i have a savings fund for college",
    "she is so serious she never laughs",
    "strange things occur in that empty house",
    "that issue has been discussed in the media",
    "are you ready to leave for work",
    "that store needs a bigger sign",
    "i will have to give it some thought",
    "i made a list of things to do",
    "you can buy an individual or group membership",
    "the appliance comes with simple instructions",
    "i paid a little more for quality shoes",
    "there is no pressure to finish right now",
    "will you accept my credit card",
    "give me your answer by noon tomorrow",
    "that test was very hard",
    "the library has many online resources",
    "i cannot identify that plant",
    "the door is on your left as you approach",
    "we will have a staff meeting after lunch",
    "eye color is genetically determined",
    "i will prepare breakfast tomorrow",
    "face masks help prevent disease",
    "choose whatever flavor you like the best",
    "failure is the back door to success",
    "it is not a good idea to argue with your boss",
    "would you like a cup of coffee",
    "it is not particularly hot outside just warm",
    "it take a large amount of food to feed an elephant",
    "he has the ability to explain things well",
    "there are five people on staff here",
    "do you recognize the person in this photo",
    "her reply indicated that she understood",
    "you can trust people of good character",
    "the company has seen strong growth this quarter",
    "the farmer suffered heavy losses after the storm",
    "set the oven to 300 degrees",
    "i wonder if the bulls will win the game",
    "the army will attack at dawn",
    "she bought herself a new coat",
    "what internet services are in your region",
    "i do not watch much television",
    "i packed my dishes in a strong box",
    "there is a good movie on tv tonight",
    "the company will pay for your training",
    "that is a pretty dress",
    "the stock market traded lower today",
    "i got a good deal at the store",
    "who do you think will win the election",
    "everybody likes ice cream",
    "keep a physical distance of six feet",
    "lay the baby in her crib please",
    "my general impression of the restaurant was good",
    "i have a good feeling about this",
    "the standard fee is 10 00 dollars",
    "the electrician will send me a bill",
    "you have a text message on your phone",
    "i fail to see what is so funny about that",
    "the cat goes outside sometimes",
    "when will your plane arrive",
    "i will give you my analysis when i have seen everything",
    "there are many health benefits to quinoa",
    "what is your name",
    "do you know the sex of your baby yet",
    "move the car forward a few feet",
    "my lawyer helped me write a will",
    "if everyone is present the meeting can begin",
    "what section of the stadium are you sitting in",
    "environmental issues are in the news",
    "glass is much heavier than plastic",
    "could you answer a question for me",
    "his best skill is woodworking",
    "my sister lives close to me",
    "the movie starts at 7 30 pm",
    "dr smith is my favorite professor",
    "the mining operation employs thousands of people",
    "i keep my accounts at my financial institution",
    "the police fight crime",
    "a caterpillar is the larval stage of a butterfly",
    "would it be ok to eat out tonight",
    "we should compare cars before we buy one",
    "city authorities make the local laws",
    "i miss you when will i see you again",
    "we need to design a new logo",
    "let us sort these beads according to color",
    "i only have one cat",
    "i will act on your information today",
    "the baby counted her ten toes",
    "do you have the knowledge to fix that",
    "gun ownership is a controversial topic",
    "there is a train station close to my house",
    "my favorite color is blue",
    "after the accident i was in a state of shock",
    "our new corporate strategy is written here",
    "i prefer little cars",
    "the instructions were clearly written",
    "we will discuss that at the meeting",
    "your mother does indeed have hearing loss",
    "it takes a lot of force to open that door",
    "please tell me the truth",
    "that is a beautiful song",
    "i need an example of that grammar point please",
    "does australia have a democratic government",
    "please check my work to be sure it is correct",
    "we live in a healthy environment",
    "the boy broke his leg",
    "turn on the light it is dark in here",
    "masks must be worn in public places",
    "that rug comes in various shades of gray",
    "would you rather have a hamburger than a hot dog",
    "that movie always makes me laugh",
    "if you do not know just guess",
    "the company s executives are paid well",
    "set the glass on the table please",
    "he needs to study for the test",
    "the employee proved his worth",
    "please hang your coat on the hook",
    "he ate the entire meal in 10 minutes",
    "there are decorative rocks in the garden",
    "the windows do not open by design",
    "have you had enough coffee",
    "do not forget to stop at the store",
    "she has not eaten since yesterday",
    "i made an insurance claim for my car accident",
    "leave me a note if you are going to be late",
    "remove the cookies from the oven",
    "the manager will look at your application",
    "could you help me move this table",
    "close the door please",
    "the dog did not make a sound",
    "i enjoy soda",
    "band is the name of our internet network",
    "the legal documents need to be signed",
    "she is very religious she attends church weekly",
    "my feet are cold",
    "please fill out this application form",
    "the divorce was final last month",
    "the main problem is a lack of money",
    "he studies health science at the university",
    "the grass is green",
    "he has a good memory",
    "they sent me a card for my birthday",
    "look on the shelf above the sink",
    "that is a comfortable seat",
    "your body is made of millions of cells",
    "they established their business in 1942",
    "that is a very nice car",
    "they are employing her on a trial basis",
    "matt is an it expert",
    "did you see that movie",
    "spring is the most beautiful season",
    "her no was very firm she will not change her mind",
    "the democrats control the senate",
    "i listen to the radio in the car",
    "we visited the museum today",
    "that store has good management",
    "she cares for her mother at home",
    "you should avoid poison ivy",
    "can you imagine if pigs could fly",
    "would you like to go out tonight",
    "that truck is huge",
    "he threw the ball to the dog",
    "i said no please do not ask again",
    "close the window please",
    "did you finish your homework",
    "you gave yourself a haircut",
    "he talks a lot",
    "in theory that is a good plan",
    "the drought had a big impact on the crops",
    "he has not responded to my text yet",
    "the police chief gave a statement to the media",
    "exercise helps you maintain a healthy weight",
    "i need to charge my phone",
    "that is a popular restaurant",
    "they serve traditional italian food there",
    "jump onto the boat and we will go fishing",
    "washing off the dirt revealed the boy s skinned knee",
    "what direction is the city from here",
    "no weapons are allowed in government buildings",
    "that store only has three employees",
    "there is cultural significance to those old ruins",
    "the carton contains a dozen egges",
    "world leaders gathered for peace talks",
    "my head hurts",
    "keep control of the car",
    "the glass has a heavy base so it will not fall over",
    "i have chest pain",
    "maria applied for the job",
    "the children play at the park",
    "measure twice cut once",
    "the doorway was very wide",
    "do not shake the can of soda",
    "we can fly to france next year",
    "my job interview went well",
    "did you manage to find the keys",
    "the table has six matching chairs",
    "i do not enjoy eating fish",
    "that particular style looks good on you",
    "i use the camera on my phone",
    "the building s structure is solid",
    "mitch is very active in politics",
    "the singer will perform tonight",
    "it rained a little bit last night",
    "keep track of your pet s weight",
    "the storm came up suddenly",
    "you will discover treasures at that thrift store",
    "there are ten candidates for the position",
    "the flag flies on the top of that building",
    "factory production has improved over the summer",
    "give yourself a treat for a job well done",
    "we are taking a trip to florida in january",
    "i am staying home this evening",
    "my bank account will affect how much i can buy",
    "the cat stays inside",
    "there will be expert presenters at the conference",
    "a foot is a unit of measure",
    "those are the best glasses to buy",
    "my dress is out of style",
    "adults pay full price but children are free",
    "do not worry about tomorrow",
    "my doctor offered me a range of options",
    "can you mention me in your story",
    "rather than focusing on the bad things let us be grateful for the good things",
    "i do not want to move far from my family",
    "that poem about life is deep",
    "please face front",
    "please do not stand so close to the edge of the cliff",
    "these potato chips are in an individual serving size package",
    "could you be more specific",
    "you are a good writer",
    "stay out of trouble",
    "it is necessary to sleep",
    "throughout my life i have always enjoyed reading",
    "i challenge you to do better",
    "do you have any fears",
    "you do not have to shoulder all the work on your own",
    "have you attended any institution of higher learning",
    "i am a middle child with one older brother and one younger sister",
    "i want to sail the seven seas",
    "i have a dream",
    "a bar is a place where alcohol is served",
    "you are beautiful",
    "do you own property like a house",
    "instead of eating cake i will have fruit",
    "i am always looking for ways to improve",
    "when i moved i realized i have a lot of stuff",
    "i claim to be a fast reader but actually i am average"
]
